### ISSUE TITLE
Missing spinner on page load

### ISSUE THREAD

**Issue by benbaker76** [MudBlazor/TryMudBlazor#154]
Hey @ScarletKuro I just wanted to bring your attention to a missing stylesheet in the `index.html` file which is why the spinner is not showing when the site loads.

```html
<link rel="stylesheet" href="css/app.css" />
```

**Comment by benbaker76** [comment]
One other issue I just noticed in the site.css file https://github.com/MudBlazor/TryMudBlazor/blob/main/src/TryMudBlazor.Client/wwwroot/css/site.css#L188

It should be:
```css
/* Editor */
#user-code-editor-container {
    overflow: hidden;
}
```

(`.` prefix should not be there)
